server:
  port: 8080

spring:
  jpa:
    open-in-view: false
    hibernate:
      dialect: org.hibernate.dialect.MySQL
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/test
    username: sa
    password:

flyway:
  user: sa
  password:
  url: jdbc:h2:file:~/test
  locations: db/migration